# Generated by Django 3.0.2 on 2020-01-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amt_worker_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Worker ID'),
        ),
    ]
