# Generated by Django 3.0.2 on 2020-01-29 21:04

import dining_room.models.website
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amt_worker_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Worker ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_management',
            field=models.ForeignKey(blank=True, default=dining_room.models.website.StudyManagement.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dining_room.StudyManagement'),
        ),
    ]
