# Generated by Django 3.0.2 on 2020-02-19 02:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room', '0003_data_add_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyaction',
            name='ax_suggestions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('at_c', "Update robot's location belief to: Couch"), ('at_dt', "Update robot's location belief to:  Dining Table"), ('at_kc', "Update robot's location belief to:  Kitchen Counter"), ('go_to_c', 'Navigate to Couch'), ('go_to_dt', 'Navigate to Dining Table'), ('go_to_kc', 'Navigate to Kitchen Counter'), ('remove_obstacle', 'Remove the obstacle blocking navigation'), ('out_of_collision', 'Move away from a collision'), ('look_at_c', 'Look at Couch'), ('look_at_dt', 'Look at Dining Table'), ('look_at_kc', 'Look at Kitchen Counter'), ('pick_bowl', 'Pick up the Bowl'), ('pick_jug', 'Pick up the Jug'), ('pick_mug', 'Pick up the Cup'), ('place', 'Put away held object'), ('restart_video', 'Restart the camera'), ('find_charger', 'Find the charger and navigate to it')], max_length=168, null=True),
        ),
        migrations.AddField(
            model_name='studyaction',
            name='dx_suggestions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lost', 'The robot is lost'), ('cannot_move', 'The robot is stuck and cannot move to a location'), ('base_collision', 'The robot has collided with an object'), ('path_blocked', "The robot's path is blocked"), ('cannot_pick', 'The cup cannot be picked up'), ('cannot_see', 'The cup is not visible'), ('different_location', 'The cup is not where it should be'), ('object_fell', "The object fell out of the robot's hand"), ('battery_low', 'The battery is low'), ('video_problem', 'There is a problem with the camera'), ('none', 'There is no problem')], max_length=129, null=True),
        ),
    ]
