# Generated by Django 3.0.2 on 2020-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room', '0003_data_add_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyaction',
            name='browser_refreshed',
            field=models.BooleanField(default=False),
        ),
    ]
